# Generated by Django 5.2.7 on 2025-10-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('lap_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lap_brand', models.CharField(max_length=10)),
                ('lap_specs', models.CharField(max_length=20)),
                ('lap_price', models.CharField(max_length=10)),
            ],
        ),
    ]
