# Generated by Django 5.2.7 on 2025-10-23 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(20), django.core.validators.RegexValidator(message='Name must contain alphabets only', regex='^[A-Za-z]+$')])),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must start with 9,8,7,6', regex='^[9876]\\d{9}$')])),
                ('imgg', models.FileField(upload_to='profile/')),
            ],
        ),
    ]
