# Generated by Django 5.2.8 on 2025-11-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('capital', models.IntegerField()),
                ('type', models.CharField(choices=[('M', 'MNC'), ('S', 'Startup')], default='S', max_length=1)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
