# Generated by Django 5.2.7 on 2025-11-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('DishId', models.IntegerField(primary_key=True, serialize=False)),
                ('DishName', models.CharField(max_length=50)),
                ('Ingredients', models.TextField()),
                ('Price', models.FloatField()),
                ('Image', models.URLField()),
            ],
        ),
    ]
