# Generated by Django 5.2.8 on 2025-11-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
