# Generated by Django 5.2.8 on 2025-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashpass_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='password',
            field=models.CharField(max_length=225),
        ),
    ]
